version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2023:2023"
    environment:
      DATABASE_URL: "postgresql://prisma:prismapassword@db:5432/mydb?schema=public"
    depends_on:
      - db
    command: /bin/sh -c "npx prisma migrate deploy && npm run start"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prismapassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
